-- Migration: Add pitch alignment columns to matches table
ALTER TABLE public.matches
ADD COLUMN IF NOT EXISTS pitch_center_lat DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS pitch_center_lng DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS pitch_angle DOUBLE PRECISION DEFAULT 0,
ADD COLUMN IF NOT EXISTS pitch_width DOUBLE PRECISION DEFAULT 95,
ADD COLUMN IF NOT EXISTS pitch_height DOUBLE PRECISION DEFAULT 55;
